#ifndef __COMMANDS_H
#define __COMMANDS_H

enum {
    MAC_TILDE = 58,
    MAC_COMMENT = 11,
    MAC_ASSIGN = 1,
    MAC_BELL = 2,
    MAC_BREAK = 3,
    MAC_CALL = 4,
    MAC_CANCEL_OFF = 5,
    MAC_CANCEL_ON = 6,
    MAC_CASE = 7,
    MAC_CASE_CALL = 8,
    MAC_CHAIN = 9,
    MAC_CHAR = 10,
    MAC_DISPLAY_OFF = 12,
    MAC_DISPLAY_ON = 13,
    MAC_ELSE = 14,
    MAC_END_FOR = 15,
    MAC_END_IF = 16,
    MAC_END_WHILE = 17,
    MAC_FOR = 18,
    MAC_FOR_EACH = 19,
    MAC_GO = 20,
    MAC_IF = 21,
    MAC_IF_EXISTS = 47,
    MAC_INPUT = 51,
    MAC_KTON = 56,
    MAC_LEN = 57,
    MAC_LABEL = 22,
    MAC_LOOK = 23,
    MAC_MACRO = 44,
    MAC_MENU_OFF = 48,
    MAC_MENU_ON = 49,
    MAC_MID = 54,
    MAC_NEST = 24,
    MAC_NEXT = 25,
    MAC_NTOK = 55,
    MAC_ON_CANCEL = 27,
    MAC_ON_ERROR = 28,
    MAC_ON_NOT_FOUND = 29,
    MAC_ORIGINAL_KEY = 46,
    MAC_PAUSE = 30,
    MAC_PAUSE_KEY = 59,
    MAC_PROMPT = 31,
    MAC_QUIT = 32,
    MAC_RESTART = 33,
    MAC_RETURN = 34,
    MAC_RETURN_CANCEL = 35,
    MAC_RETURN_ERROR = 36,
    MAC_RETURN_NOT_FOUND = 37,
    MAC_SHELL_MACRO = 26,
    MAC_SPEED = 38,
    MAC_STATE = 41,
    MAC_STATUS_PROMPT = 50,
    MAC_STEP_OFF = 45,
    MAC_STEP_ON = 39,
    MAC_SYSTEM = 53,
    MAC_TEXT = 40,
    MAC_VARIABLE = 52,
    MAC_WAIT = 42,
    MAC_WHILE = 43,

    // Undocumented!
    MAC_OTHERWISE = 61,
};

static const char *kMacroNames[UINT8_MAX] = {
    [MAC_TILDE] = "~",
    [MAC_COMMENT] = ";",
    [MAC_ASSIGN] = "ASSIGN",
    [MAC_BELL] = "BELL",
    [MAC_BREAK] = "BREAK",
    [MAC_CALL] = "CALL",
    [MAC_CANCEL_OFF] = "CANCEL OFF",
    [MAC_CANCEL_ON] = "CANCEL ON",
    [MAC_CASE] = "CASE",
    [MAC_CASE_CALL] = "CASE CALL",
    [MAC_CHAIN] = "CHAIN",
    [MAC_CHAR] = "CHAR",
    [MAC_DISPLAY_OFF] = "DISPLAY OFF",
    [MAC_DISPLAY_ON] = "DISPLAY ON",
    [MAC_ELSE] = "ELSE",
    [MAC_END_FOR] = "END FOR",
    [MAC_END_IF] = "END IF",
    [MAC_END_WHILE] = "END WHILE",
    [MAC_FOR] = "FOR",
    [MAC_FOR_EACH] = "FOR EACH",
    [MAC_GO] = "GO",
    [MAC_IF] = "IF",
    [MAC_IF_EXISTS] = "IF EXISTS",
    [MAC_INPUT] = "INPUT",
    [MAC_KTON] = "KTON",
    [MAC_LEN] = "LEN",
    [MAC_LABEL] = "LABEL",
    [MAC_LOOK] = "LOOK",
    [MAC_MACRO] = "Macro Commands",
    [MAC_MENU_OFF] = "MENU OFF",
    [MAC_MENU_ON] = "MENU ON",
    [MAC_MID] = "MID",
    [MAC_NEST] = "NEST",
    [MAC_NEXT] = "NEXT",
    [MAC_NTOK] = "NTOK",
    [MAC_ON_CANCEL] = "ON CANCEL",
    [MAC_ON_ERROR] = "ON ERROR",
    [MAC_ON_NOT_FOUND] = "ON NOT FOUND",
    [MAC_ORIGINAL_KEY] = "ORIGINAL KEY",
    [MAC_PAUSE] = "PAUSE",
    [MAC_PAUSE_KEY] = "PAUSE KEY",
    [MAC_PROMPT] = "PROMPT",
    [MAC_QUIT] = "QUIT",
    [MAC_RESTART] = "RESTART",
    [MAC_RETURN] = "RETURN",
    [MAC_RETURN_CANCEL] = "RETURN CANCEL",
    [MAC_RETURN_ERROR] = "RETURN ERROR",
    [MAC_RETURN_NOT_FOUND] = "RETURN NOT FOUND",
    [MAC_SHELL_MACRO] = "SHELL MACRO",
    [MAC_SPEED] = "SPEED",
    [MAC_STATE] = "STATE",
    [MAC_STATUS_PROMPT] = "STATUS PROMPT",
    [MAC_STEP_OFF] = "STEP OFF",
    [MAC_STEP_ON] = "STEP ON",
    [MAC_SYSTEM] = "SYSTEM",
    [MAC_TEXT] = "TEXT",
    [MAC_VARIABLE] = "VARIABLE",
    [MAC_WAIT] = "WAIT",
    [MAC_WHILE] = "WHILE",
    [MAC_OTHERWISE] = "OTHERWISE",
};

static const char *kFunctionKeys[UINT8_MAX] = {
    "Compose",
    "^A",
    "^B",
    "^C",
    "^D",
    "^E",
    "^F",
    "^G",
    "^H",
    "Tab",
    "Enter",
    "^K",
    "^L",
    "^M",
    "^N",
    "^O",
    "^P",
    "^Q",
    "^R",
    "^S",
    "^T",
    "^U",
    "^V",
    "Up",
    "Right",
    "Left",
    "Down",
    "^[",
    "^\\",
    "^]",
    "^^",
    "^_",
    "Cancel",
    "Forward Search",
    "Help",
    "Indent",
    "List Files",
    "Bold",
    "Exit",
    "Underline",
    "Merge Return",
    "Save",
    "F11",
    "F12",
    "Setup",
    "Backward Search",
    "Switch",
    "Left/Right Indent",
    "Date/Outline",
    "Center",
    "Print",
    "Format",
    "Merge Commands",
    "Retrieve",
    "Shift-F11",
    "Shift-F12",
    "Thesaurus",
    "Search/Replace",
    "Reveal Codes",
    "Block",
    "Mark Text",
    "Flush Right",
    "Columns/Table",
    "Style",
    "Graphics",
    "Macro",
    "Alt-F11",
    "Alt-F12",
    "Shell",
    "Spell",
    "Screen",
    "Move",
    "Text In/Out",
    "Tab Align",
    "Footnote",
    "Font",
    "Merge/Sort",
    "Define Macro",
    "Ctrl-F11",
    "Ctrl-F12",
    "Backspace",
    "Del",
    "Delete Word",
    "Word Right",
    "Word Left",
    "Home, Home, Right",
    "Home, Home, Left",
    "Reserved",
    "Go To",
    "PgUp",
    "PgDn",
    "Screen Down",
    "Screen Up",
    "Typeover",
    "Left Mar Rel",
    "HPg",
    "Soft Hyphen",
    "Hard Hyphen",
    "Hard Space",
    [107] = "Menu Bar",
    [109] = "Block Move",
    [110] = "Block Copy",
    [125] = "Mouse Event",
};

#endif
